### PR TITLE
Upgrade neovim to version > 0.9

### PR DESCRIPTION
**Pull request by mav3ri3k**
The current version is 0.6.1 which is archaic in internet's timeframe, my config keeps breaking.

### CODE REVIEW

**Comment by mav3ri3k** [comment]
@rust-lang/infra

**Comment by jdno** [comment]
We're installing most packages from the default package repository, which in the case of the dev-desktops is a bit outdated. The machines are still running Ubuntu 22.04 LTS, which only [ships with 0.6.1](https://packages.ubuntu.com/jammy/neovim).

We will probably upgrade the machines to 24.04 in the coming months, which [updates neovim to 0.9.5](https://packages.ubuntu.com/noble/neovim). Alternatively, we can also install the latest version [from a PPA](https://packages.ubuntu.com/noble/neovim). But the PPA isn't managed by the neovim maintainers, so I would personally prefer to wait until we upgrade the machines.

**Comment by MarcoIeni** [comment]
I updated `dev-desktop-staging.infra.rust-lang.org` to ubuntu 24. I'll update the other VMs soon!

**Comment by MarcoIeni** [comment]
neovim 0.9 is now available in `dev-desktop-us-1`. More info in [zulip](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/dev-desktops.20maintenance/near/467857063)

**Comment by mav3ri3k** [comment]
Wonderful stuff! Thanks.

**Pull request closed without merging**
