### PR TITLE
Add podman to dev desktop

### PR DESCRIPTION
**Pull request by fee1-dead**
per [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Cloud.20desktop.20package.20request)

### CODE REVIEW

**Comment by albertlarsan68** [comment]
I think there may be more steps than just adding podman to the apt install list.

**Comment by fee1-dead** [comment]
> I think there may be more steps than just adding podman to the apt install list.

Per the [installation instructions](https://podman.io/docs/installation) on their site, I don't see additional steps required other than installing from the package manager.

**Comment by albertlarsan68** [comment]
Per [this other official doc page](https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md), it requires a bit of setup to make sure non-root users have access.

**Comment by fee1-dead** [comment]
Ah I see. Then I don't think I can write an ansible config for that since I don't have a lot of experience in ansible.

**Comment by jdno** [comment]
Thanks for the links. 🙂

I had a brief look at the installation guide and the only thing that stands out as a potential issue is reserving UIDs in `/etc/subuid`. Since we create users dynamically from rust-lang/team, this might get annoying to automate.

I'll try to make some time either tomorrow or next week to do look more into this.

**Comment by Nilstrieb** [comment]
@jdno friendly ping in case you forgot about it :)

**Comment by jdno** [comment]
Oh my time is flying 😱 I haven't forgotten about it, but I also need to block some dedicated time next week. 🤦‍♂️

**Comment by jdno** [comment]
I've installed Podman on `dev-desktop-staging`. Still need to do a few more tests, but feel free to poke it as well and let me know if you find any issues.

**Comment by jdno** [comment]
I've created a new pull request for my branch that installs Podman and configures the rootless mode here: https://github.com/rust-lang/simpleinfra/pull/320. I'll give folks a chance to review it, and plan to deploy it to production after the weekend.

**Comment by jdno** [comment]
I've deployed the other PR to the dev-desktops last week, so Podman should be available and usable for everyone. If that's not the case, let me know. Otherwise we can probably close this PR. :)

**Pull request closed without merging**
