### PR TITLE
assign `bastion` domain to ubuntu 24 ec2

### PR DESCRIPTION
**Pull request by MarcoIeni**
- [ ] apply after https://github.com/rust-lang/simpleinfra/pull/594

### CODE REVIEW

**Comment by MarcoIeni** [comment]
Can we assign the same domain to multiple ec2?

**Comment by jdno** [comment]
Theoretically yes, but it won't do what you want it to do. 😅 But why can't we just move it from the old to the new host? Right now, it seems that between the two PRs there will be a moment in time where the domain is not directed at any host.

**Comment by MarcoIeni** [comment]
I was worried that assigning the same domain to two ec2 will result in an error. I'll open a new pr

**Comment by MarcoIeni** [comment]
closing in favor of https://github.com/rust-lang/simpleinfra/pull/598

**Pull request closed without merging**
