### PR TITLE
update `hashicorp/random` to 3.6.2

### PR DESCRIPTION
**Pull request by MarcoIeni**
## Why this PR

- [x] remove bors from this PR

Related to #437 

I found out that updating one package at a time is difficult because packages depend from each other.

So I changed approach, and decided to update a dependency at a time.

I started with `hashicorp/random` because old versions of this dependency aren't compatible with arm which makes impossible to upgrade any other dependency.

While working on this, I also needed to update also AWS version to be able to run `terra* plan`.

## How I created this PR

- I ran `rg "hashicorp/random" -.` to find every terragrunt state and terraform module that depends on `hashicorp/random`.
- I ran `terragrunt init --upgrade` or `terraform init --upgrade` on each one.

## Can we merge it?

We can only merge this PR after we applied all the changes (if any). Here's the status of each `terra* apply`:

- [x] `terraform/docs-rs/`: no `apply` needed
- [ ] `terraform/monitorbot/`: needs `apply`. JD agreed to apply this
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.monitorbot.aws_ecs_task_definition.task must be replaced
-/+ resource "aws_ecs_task_definition" "task" {
      ~ arn                      = "arn:aws:ecs:us-west-1:890664054962:task-definition/monitorbot:6" -> (known after apply)
      ~ arn_without_revision     = "arn:aws:ecs:us-west-1:890664054962:task-definition/monitorbot" -> (known after apply)
      ~ container_definitions    = jsonencode(
          ~ [
              ~ {
                  - cpu              = 0
                  + dockerLabels     = {}
                    name             = "app"
                  - volumesFrom      = []
                    # (7 unchanged attributes hidden)
                },
            ] # forces replacement
        )
      ~ id                       = "monitorbot" -> (known after apply)
      ~ revision                 = 6 -> (known after apply)
      - tags                     = {} -> null
      ~ tags_all                 = {} -> (known after apply)
        # (8 unchanged attributes hidden)

      + ephemeral_storage { # forces replacement
          + size_in_gib = 21 # forces replacement
        }
    }

  # module.monitorbot.module.ecs_service.aws_ecs_service.service will be updated in-place
  ~ resource "aws_ecs_service" "service" {
        id                                 = "arn:aws:ecs:us-west-1:890664054962:service/rust-ecs-prod/monitorbot"
        name                               = "monitorbot"
        tags                               = {}
      ~ task_definition                    = "arn:aws:ecs:us-west-1:890664054962:task-definition/monitorbot:6" -> (known after apply)
        # (15 unchanged attributes hidden)

        # (4 unchanged blocks hidden)
    }

Plan: 1 to add, 1 to change, 1 to destroy.
```
- [x] `terraform/rds-databases/`:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # postgresql_grant.rw_self_sequence["discord-mods-bot"] must be replaced
-/+ resource "postgresql_grant" "rw_self_sequence" {
      ~ id                = "discord-mods-bot_discord-mods-bot_public_sequence" -> (known after apply)
      ~ privileges        = [ # forces replacement
          + "SELECT",
          + "UPDATE",
          + "USAGE",
        ]
        # (5 unchanged attributes hidden)
    }

  # postgresql_grant.rw_self_sequence["rustc_perf"] must be replaced
-/+ resource "postgresql_grant" "rw_self_sequence" {
      ~ id                = "rustc_perf_rustc_perf_public_sequence" -> (known after apply)
      ~ privileges        = [ # forces replacement
          + "SELECT",
          + "UPDATE",
          + "USAGE",
        ]
        # (5 unchanged attributes hidden)
    }

  # postgresql_grant.rw_self_sequence["triagebot"] must be replaced
-/+ resource "postgresql_grant" "rw_self_sequence" {
      ~ id                = "triagebot_triagebot_public_sequence" -> (known after apply)
      ~ privileges        = [ # forces replacement
          + "SELECT",
          + "UPDATE",
          + "USAGE",
        ]
        # (5 unchanged attributes hidden)
    }

  # postgresql_grant.rw_self_tables["discord-mods-bot"] must be replaced
-/+ resource "postgresql_grant" "rw_self_tables" {
      ~ id                = "discord-mods-bot_discord-mods-bot_public_table" -> (known after apply)
      ~ privileges        = [ # forces replacement
          + "DELETE",
          + "INSERT",
          + "REFERENCES",
          + "SELECT",
          + "TRIGGER",
          + "TRUNCATE",
          + "UPDATE",
        ]
        # (5 unchanged attributes hidden)
    }

  # postgresql_grant.rw_self_tables["rustc_perf"] must be replaced
-/+ resource "postgresql_grant" "rw_self_tables" {
      ~ id                = "rustc_perf_rustc_perf_public_table" -> (known after apply)
      ~ privileges        = [ # forces replacement
          + "DELETE",
          + "INSERT",
          + "REFERENCES",
          + "SELECT",
          + "TRIGGER",
          + "TRUNCATE",
          + "UPDATE",
        ]
        # (5 unchanged attributes hidden)
    }

  # postgresql_grant.rw_self_tables["triagebot"] must be replaced
-/+ resource "postgresql_grant" "rw_self_tables" {
      ~ id                = "triagebot_triagebot_public_table" -> (known after apply)
      ~ privileges        = [ # forces replacement
          + "DELETE",
          + "INSERT",
          + "REFERENCES",
          + "SELECT",
          + "TRIGGER",
          + "TRUNCATE",
          + "UPDATE",
        ]
        # (5 unchanged attributes hidden)
    }

Plan: 6 to add, 0 to change, 6 to destroy.

```
- [ ] `terragrunt/accounts/bors-prod/app/`: needs `apply`
```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_vpc_security_group_ingress_rule.ingress_ecs will be updated in-place
  ~ resource "aws_vpc_security_group_ingress_rule" "ingress_ecs" {
        id                           = "sgr-017b4ff5e204dc899"
      ~ ip_protocol                  = "tcp" -> "TCP"
        # (7 unchanged attributes hidden)
    }

  # aws_vpc_security_group_ingress_rule.ingress_lb["subnet-04bb24d3845ea6d81"] will be updated in-place
  ~ resource "aws_vpc_security_group_ingress_rule" "ingress_lb" {
        id                     = "sgr-0a16bc64b3ae22d57"
      ~ ip_protocol            = "tcp" -> "TCP"
        # (7 unchanged attributes hidden)
    }

  # aws_vpc_security_group_ingress_rule.ingress_lb["subnet-094ad4148fc34d875"] will be updated in-place
  ~ resource "aws_vpc_security_group_ingress_rule" "ingress_lb" {
        id                     = "sgr-0f2f71f1e66842037"
      ~ ip_protocol            = "tcp" -> "TCP"
        # (7 unchanged attributes hidden)
    }

  # aws_vpc_security_group_ingress_rule.ingress_lb["subnet-09d7a71ee43791afb"] will be updated in-place
  ~ resource "aws_vpc_security_group_ingress_rule" "ingress_lb" {
        id                     = "sgr-0a468b2f3d9df45db"
      ~ ip_protocol            = "tcp" -> "TCP"
        # (7 unchanged attributes hidden)
    }

Plan: 0 to add, 4 to change, 0 to destroy.
```
- [ ] `terragrunt/accounts/bors-staging/app/`:
```
  # aws_vpc_security_group_ingress_rule.ingress_ecs will be updated in-place
  ~ resource "aws_vpc_security_group_ingress_rule" "ingress_ecs" {
        id                           = "sgr-08e3e86c9472001f2"
      ~ ip_protocol                  = "tcp" -> "TCP"
        # (7 unchanged attributes hidden)
    }

  # aws_vpc_security_group_ingress_rule.ingress_lb["subnet-0046e974b9a7032ee"] will be updated in-place
  ~ resource "aws_vpc_security_group_ingress_rule" "ingress_lb" {
        id                     = "sgr-0e802d6d16a7f7eab"
      ~ ip_protocol            = "tcp" -> "TCP"
        # (7 unchanged attributes hidden)
    }

  # aws_vpc_security_group_ingress_rule.ingress_lb["subnet-07cdc304431cb6210"] will be updated in-place
  ~ resource "aws_vpc_security_group_ingress_rule" "ingress_lb" {
        id                     = "sgr-0adeebe4c72d6dfc8"
      ~ ip_protocol            = "tcp" -> "TCP"
        # (7 unchanged attributes hidden)
    }

  # aws_vpc_security_group_ingress_rule.ingress_lb["subnet-0f4430084ef4e1b0a"] will be updated in-place
  ~ resource "aws_vpc_security_group_ingress_rule" "ingress_lb" {
        id                     = "sgr-0332ee4c90b3a8950"
      ~ ip_protocol            = "tcp" -> "TCP"
        # (7 unchanged attributes hidden)
    }

Plan: 0 to add, 4 to change, 0 to destroy.
```
- [x] `terragrunt/accounts/docs-rs-staging/docs-rs/`: doesn't need `apply`

### CODE REVIEW

**Comment by MarcoIeni** [comment]
It would be super cool if the `Can we merge it?` section of the PR body was generated from CI as it takes a lot of manual work

**Comment by MarcoIeni** [comment]
Reviewers: let me know if the terraform changes are safe to apply 🙏

**Review by jdno — APPROVED** [review]
:+1:

**Comment by MarcoIeni** [comment]
Applied everything except bors-prod. Waiting for Jakub response [here](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Infra.20.60apply.60.20log/near/460073559) 👍

**Pull request merged**
