### PR TITLE
chore(bastion): allow ubuntu user

### PR DESCRIPTION
**Pull request by MarcoIeni**
I need this to apply ansible for the first time

### CODE REVIEW

**Comment by MarcoIeni** [comment]
I couldn't apply this because I can't set my ip twice (I tried to set my ip to the ubuntu user as well).

**Comment by jdno** [comment]
We want to drop the firewall in #578 anyways, right? Should we deploy and merge that to unblock this one?

**Comment by MarcoIeni** [comment]
Still can't `ssh ubuntu@bastion2.infra.rust-lang.org` D: so yeah, dropping the ip requirement will make things easier for sure

**Comment by MarcoIeni** [comment]
EDIT: I managed by using the ip instead of the url

**Pull request merged**
