### PR TITLE
Add measureme to list of bors repos

### PR DESCRIPTION
**Pull request by rylev**
r? @pietroalbini

### CODE REVIEW

**Comment by rylev** [comment]
CI is failing for the reasons that are fixed in https://github.com/rust-lang/simpleinfra/pull/74

**Review by pietroalbini — APPROVED** [review]

**Comment by pietroalbini** [comment]
@Mark-Simulacrum could you apply this?

**Comment by Mark-Simulacrum** [comment]
Yeah I'll take care of this in a bit

**Comment by Mark-Simulacrum** [comment]
Done -- not sure if github will realize, but this change is now empty on master.

**Pull request closed without merging**
