### PR TITLE
Update list of infra-admins

### PR DESCRIPTION
**Pull request by jdno**
aidanhs has left the infra-team, and jdn has joined the infra-admins.

### CODE REVIEW

**Review by rylev — COMMENTED** [review]
Can we bring the list of admins in from somewhere else so that we don't have to repeat it in all the config files?

**Comment by jdno** [comment]
I'm not sure if there was a reason that this was defined on a per-playbook level. @pietroalbini, do you know more about this?

**Comment by pietroalbini** [comment]
We can definitely have the list of admins somewhere, even though we should allow to have extra sudo users (and not hardcode it to just admins). Maybe set the list in `group_vars/all.yml`?

**Comment by jdno** [comment]
Done. :+1:

**Review by rylev — APPROVED** [review]

**Comment by pietroalbini** [comment]
Deployed across all playbooks.

**Pull request merged**
